# Generated by Django 4.2 on 2023-04-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=300)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("cpf", models.CharField(blank=True, max_length=15, null=True)),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "endereco_logradouro",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "endereco_numero",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "endereco_complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "endereco_cep",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "endereco_bairro",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "endereco_cidade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "endereco_estado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
            ],
        ),
    ]
