# Generated by Django 4.2 on 2023-05-14 02:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("siscostura", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="cliente",
            managers=[
                ("objetos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelTable(
            name="cliente",
            table="cliente",
        ),
    ]
